

FROM python:3.12

WORKDIR /



COPY CLI /CLI
COPY logs /logs
COPY requirements.txt .

VOLUME /projects

RUN pip install pytermgui requests python-dotenv PyYAML



#RUN  pip install --no-cache-dir -r requirements.txt


#CMD ["python", "CLI/main.py"]


