


FROM python:3.12

WORKDIR /

COPY requirements.txt .

RUN  pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn flask pm4py pandas numpy python-dotenv tqdm scikit-learn torch



COPY server /server 
COPY logs /logs
VOLUME /projects

ENV SERVER_PORT=5000

EXPOSE 5000

CMD ["gunicorn", "-b", ":5000","server.server:app", "--timeout", "1800"]

