


FROM python:3.12

WORKDIR /

COPY server /server 
COPY requirements.txt .


VOLUME /projects


#RUN pip install -r ./requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip pip install --no-cache-dir -r requirements.txt



