

FROM python:3.12

WORKDIR /



COPY CLI /CLI
COPY logs /logs
COPY requirements.txt .

VOLUME /projects

RUN pip install pytermgui requests python-dotenv PyYAML



# after running docker compose, use docker's interactive terminal
# first run `docker-compose exec cli sh`
# inside the interactive terminal, run `python CLI/main.py`

