name: spp_process_discovery
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy>=1.18.5
  - pytorch
  - pandas
  - pydoc-markdown
  - flask
  - werkzeug==2.0
  - pip
  - pip:
    - pm4py
    - scikit-learn
    - typing_extensions>=3.10.0.0
    - python-dotenv
    - pytermgui
