site_name: ProcessProphet docs 

theme:
  name: "material"


plugins:
  - mkdocstrings

nav: 
  - Home: index.md
  - Docs:
    - API documentation: server_routes.md
    - Backend: managers.md
    - RMTPP torch: RMTPP_torch.md
    - CLI: CLI.md